document.write("<div id='cls'></div>");
let div = document.getElementById("cls");
div.innerHTML="Дюбель — конструктивный элемент, который используется для укрепления винта или предмета настене, на потолке или на полу в помещении или под открытым небом в различных материалах(бетон, кирпич и прочее). Сам дюбель удерживается в конструкции при помощи сил трения. Снекоторого времени элементы связи и укрепления, дюбели и винт (шуруп) объединяют в одноцелое и используются, прежде всего, для тяжёлых нагрузок. Дюбели предлагаются в различныхвеличинах, которые руководствуются диаметром дюбеля (и соответственно необходимымотверстием), измеренным в миллиметрах.."
div.style.background="#f0f";
div.style.color="#99ffff";
div.style.width="50%";
div.style.outline="10px dotted #000";
div.className="gls";
let sec = document.querySelector(".gls");
sec.style.fontSize="12pt";
sec.style.fontWeight="bold";
sec.style.textDecoration="line-through";